// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HLGranite.Drawing</NameSpace><Collection>IList</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HLGranite.Drawing
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Windows.Shapes;
    using Thought.vCards;


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Project))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryWIP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Inventory))]
    public partial class BaseAttribute
    {

        private string guidField;

        private Employee creatorField;

        protected System.DateTime date;

        private string notesField;

        private Object tagField;

        /// <summary>
        /// BaseAttribute class constructor
        /// </summary>
        public BaseAttribute()
        {
            this.tagField = new Object();
            this.creatorField = new Employee();
        }

        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public Employee creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }

        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        public Object Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }

    public partial class Employee : User
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    public partial class User : vCard
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warehouse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stock))]
    public partial class BaseElement
    {

        private string codeField;

        private string name1Field;

        private string name2Field;

        private string notesField;

        private Object tagField;

        /// <summary>
        /// BaseElement class constructor
        /// </summary>
        public BaseElement()
        {
            this.tagField = new Object();
        }

        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        public string Name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }

        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }

        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        public Object Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }

    public partial class Warehouse : BaseElement
    {
        private vCardDeliveryAddressCollection addressField;

        public vCardDeliveryAddressCollection Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }

    public partial class Stock : BaseElement
    {
    }

    public partial class Customer : User
    {
    }

    public partial class Project : BaseAttribute
    {

        private System.DateTime createdAtField;

        private Employee createdByField;

        private IList<WorkOrder> workOrderField;

        private decimal progressField;

        /// <summary>
        /// Project class constructor
        /// </summary>
        public Project()
        {
            this.createdByField = new Employee();
        }

        public System.DateTime CreatedAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }

        /// <summary>
        /// Gets or sets created person. Normally is the planner.
        /// </summary>
        public Employee CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }

        /// <summary>
        /// Gets or sets work order collection for this project.
        /// </summary>
        public IList<WorkOrder> WorkOrder
        {
            get
            {
                return this.workOrderField;
            }
            set
            {
                this.workOrderField = value;
            }
        }

        /// <summary>
        /// Overall progress in percentage for this project only.
        /// It may contains multiple of work order.
        /// </summary>
        public decimal Progress
        {
            get
            {
                return this.progressField;
            }
            set
            {
                this.progressField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryWIP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Inventory))]
    public partial class BaseItem : BaseAttribute
    {

        protected int width;

        protected int height;

        private Unit uomField;

        /// <summary>
        /// Gets or sets Unit of measurement.
        /// </summary>
        public Unit Uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }
    }

    public enum Unit
    {

        /// <remarks/>
        Cm,

        /// <remarks/>
        Inch,

        /// <remarks/>
        Meter,

        /// <remarks/>
        Feet,
    }

    public partial class WorkItem : BaseItem
    {

        private System.DateTime createdAtField;

        private Employee workedByField;

        private int minWidthField;

        private int minHeightField;

        private decimal progressField;

        private IList<WorkItem> childField;

        /// <summary>
        /// WorkItem class constructor
        /// </summary>
        public WorkItem()
        {
            this.childField = new System.Collections.Generic.List<WorkItem>();
            this.workedByField = new Employee();
        }

        public System.DateTime CreatedAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }

        public Employee WorkedBy
        {
            get
            {
                return this.workedByField;
            }
            set
            {
                this.workedByField = value;
            }
        }

        public int MinWidth
        {
            get
            {
                return this.minWidthField;
            }
            set
            {
                this.minWidthField = value;
            }
        }

        public int MinHeight
        {
            get
            {
                return this.minHeightField;
            }
            set
            {
                this.minHeightField = value;
            }
        }

        /// <summary>
        /// Progress in percentage for this work item only.
        /// </summary>
        public decimal Progress
        {
            get
            {
                return this.progressField;
            }
            set
            {
                this.progressField = value;
            }
        }

        public IList<WorkItem> Child
        {
            get
            {
                return this.childField;
            }
            set
            {
                this.childField = value;
            }
        }
    }

    public partial class InventoryWIP : BaseItem
    {

        private Employee workedByField;

        private System.DateTime workedAtField;

        /// <summary>
        /// InventoryWIP class constructor
        /// </summary>
        public InventoryWIP()
        {
            this.workedByField = new Employee();
        }

        public Employee WorkedBy
        {
            get
            {
                return this.workedByField;
            }
            set
            {
                this.workedByField = value;
            }
        }

        public System.DateTime WorkedAt
        {
            get
            {
                return this.workedAtField;
            }
            set
            {
                this.workedAtField = value;
            }
        }

        public int Width
        {
            get
            {
                return base.width;
            }
            set
            {
                base.width = value;
            }
        }

        public int Height
        {
            get
            {
                return base.height;
            }
            set
            {
                base.height = value;
            }
        }
    }

    public partial class Inventory : BaseItem
    {

        private System.DateTime purchaseAtField;

        private Stock stockField;

        private Warehouse warehouseField;

        /// <summary>
        /// Inventory class constructor.
        /// </summary>
        public Inventory()
        {
            this.warehouseField = new Warehouse();
            this.stockField = new Stock();
        }

        public System.DateTime PurchaseAt
        {
            get
            {
                return this.purchaseAtField;
            }
            set
            {
                this.purchaseAtField = value;
            }
        }

        public int Width
        {
            get
            {
                return base.width;
            }
            set
            {
                base.width = value;
            }
        }

        public int Height
        {
            get
            {
                return base.height;
            }
            set
            {
                base.height = value;
            }
        }

        public Stock Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }

        public Warehouse Warehouse
        {
            get
            {
                return this.warehouseField;
            }
            set
            {
                this.warehouseField = value;
            }
        }
    }

    public partial class Bullnose
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warehouses))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Users))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stocks))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Projects))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Inventories))]
    public partial class DatabaseObject
    {
    }

    public partial class Warehouses : DatabaseObject
    {

        private IList<Warehouse> warehouseField;

        /// <summary>
        /// Warehouses class constructor
        /// </summary>
        public Warehouses()
        {
            this.warehouseField = new System.Collections.Generic.List<Warehouse>();
        }

        public IList<Warehouse> Warehouse
        {
            get
            {
                return this.warehouseField;
            }
            set
            {
                this.warehouseField = value;
            }
        }
    }

    public partial class Users : DatabaseObject
    {

        private IList<User> userField;

        /// <summary>
        /// Users class constructor
        /// </summary>
        public Users()
        {
            this.userField = new System.Collections.Generic.List<User>();
        }

        public IList<User> User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    public partial class Stocks : DatabaseObject
    {

        private IList<Stock> stockField;

        /// <summary>
        /// Stocks class constructor
        /// </summary>
        public Stocks()
        {
            this.stockField = new System.Collections.Generic.List<Stock>();
        }

        public IList<Stock> Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
    }

    public partial class Projects : DatabaseObject
    {

        private IList<Project> projectField;

        /// <summary>
        /// Projects class constructor
        /// </summary>
        public Projects()
        {
            this.projectField = new System.Collections.Generic.List<Project>();
        }

        public IList<Project> Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
    }

    public partial class Inventories : DatabaseObject
    {

        private IList<Inventory> inventoryField;

        /// <summary>
        /// Inventories class constructor
        /// </summary>
        public Inventories()
        {
            this.inventoryField = new System.Collections.Generic.List<Inventory>();
        }

        public IList<Inventory> Inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
    }

    public partial class EllipseItem : ShapeItem
    {

        public int Width
        {
            get
            {
                return base.width;
            }
            set
            {
                base.width = value;
            }
        }

        public int Height
        {
            get
            {
                return base.height;
            }
            set
            {
                base.height = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RectItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(U))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Triangle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(L))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EllipseItem))]
    public partial class ShapeItem : Shape
    {
        protected int width;

        protected int height;
    }

    public partial class RectItem : ShapeItem
    {

        public int Width
        {
            get
            {
                return base.width;
            }
            set
            {
                base.height = value;
            }
        }

        public int Height
        {
            get
            {
                return base.height;
            }
            set
            {
                base.height = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(U))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Triangle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(L))]
    public partial class PolygonItem : ShapeItem
    {
    }

    public partial class U : PolygonItem
    {
    }

    public partial class Triangle : PolygonItem
    {
    }

    public partial class L : PolygonItem
    {
    }

    public partial class InventoryManager
    {
    }

    public partial class LengthItem
    {

        private int lengthField;

        private Bullnose typeField;

        public int Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        public Bullnose Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    public partial class Lengths
    {

        private IList<LengthItem> lengthItemField;

        /// <summary>
        /// Lengths class constructor
        /// </summary>
        public Lengths()
        {
            this.lengthItemField = new System.Collections.Generic.List<LengthItem>();
        }

        public IList<LengthItem> LengthItem
        {
            get
            {
                return this.lengthItemField;
            }
            set
            {
                this.lengthItemField = value;
            }
        }
    }

    public partial class WorkItemCollection
    {

        private IList<WorkItem> workItemField;

        /// <summary>
        /// WorkItemCollection class constructor
        /// </summary>
        public WorkItemCollection()
        {
            this.workItemField = new System.Collections.Generic.List<WorkItem>();
        }

        public IList<WorkItem> WorkItem
        {
            get
            {
                return this.workItemField;
            }
            set
            {
                this.workItemField = value;
            }
        }
    }

    public partial class WorkOrder
    {

        private string guidField;

        private IList<WorkItem> workItemField;

        /// <summary>
        /// WorkOrder class constructor
        /// </summary>
        public WorkOrder()
        {
            this.workItemField = new System.Collections.Generic.List<WorkItem>();
        }

        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public IList<WorkItem> WorkItem
        {
            get
            {
                return this.workItemField;
            }
            set
            {
                this.workItemField = value;
            }
        }
    }
}